FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
RUN git clone https://github.com/d3fenddr/RestaurantApp.git .
WORKDIR /src/RestaurantAPI/RestaurantAPI
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://0.0.0.0:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "RestaurantAPI.dll"]


